const actionTypes = {
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",
  GET_POSTS: 'GET_POSTS',
  GET_POST_LIMIT:'GET_POSTS_LIMIT',
  GET_CATEGORIES: 'GET_CATEGORIES',
  GET_PRICES: 'GET_PRICES',
  GET_AREA:'GET_AREA',
  GET_NEW_POST: "GET_NEW_POST",
  GET_PROVINCE:"GET_PROVINCE"
};

export default actionTypes;
