const actionTypes = {
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",
  GET_POSTS: 'GET_POSTS',
  GET_POST_LIMIT:'GET_POSTS_LIMIT',
  GET_CATEGORIES: 'GET_CATEGORIES',
  GET_PRICES: 'GET_PRICES',
  GET_AREA:'GET_AREA',
  GET_NEW_POST: "GET_NEW_POST",
  GET_PROVINCE:"GET_PROVINCE",
  GET_POST_ADMIN:"GET_POST_ADMIN",
  EDIT_DATA:"EDIT_DATA",
  RESET_EDIT_DATA:"RESET_EDIT_DATA",
  //USER
  GET_CURRENT:'GET_CURRENT',
  GET_USER_LIMIT:'GET_USER_LIMIT'
};

export default actionTypes;
